[package]
name = "unit_converter"
version = "0.1.0"
authors = ["y² <yy@yuyuan.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

unitverse = { path = "../unitverse" }